export const materiasMock = [
  {
    id: 1,
    nombre: 'Temas de filosofía',
    clave: 'TMFLS',
    horas_semana: 6,
    semestre: 'Sexto',
  },
  {
    id: 2,
    nombre: 'Ciencias Sociales III',
    clave: 'CSIII',
    horas_semana: 4,
    semestre: 'Cuarto',
  },
  {
    id: 3,
    nombre: 'Reacciones Químicas',
    clave: 'RECQM',
    horas_semana: 6,
    semestre: 'Cuarto',
  },
  {
    id: 4,
    nombre: 'Conservación de la energía y sus interacciones',
    clave: 'CSVEI',
    horas_semana: 6,
    semestre: 'Segundo',
  },
  {
    id: 5,
    nombre: 'Lengua y Comunicación II',
    clave: 'LYCII',
    horas_semana: 6,
    semestre: 'Segundo',
  },
  {
    id: 6,
    nombre: 'Temas Selectos de Matemáticas',
    clave: 'TSMAT',
    horas_semana: 8,
    semestre: 'Cuarto',
  },
  {
    id: 7,
    nombre: 'Pensamiento Matemático',
    clave: 'PSMAT',
    horas_semana: 4,
    semestre: 'Segundo',
  },
  {
    id: 8,
    nombre: 'Dibujo Técnico',
    clave: 'DBTEC',
    horas_semana: 6,
    semestre: 'Sexto',
  },
  {
    id: 9,
    nombre: 'Cultura Digital II',
    clave: 'CLDGT',
    horas_semana: 4,
    semestre: 'Segundo',
  },
  {
    id: 10,
    nombre: 'Conciencia Histórica',
    clave: 'CNHST',
    horas_semana: 3,
    semestre: 'Cuarto',
  },
  {
    id: 11,
    nombre: 'Inglés II',
    clave: 'INGII',
    horas_semana: 8,
    semestre: 'Segundo',
  },
  {
    id: 12,
    nombre: 'Inglés IV',
    clave: 'INGII',
    horas_semana: 5,
    semestre: 'Cuarto',
  },
  {
    id: 13,
    nombre: 'Inglés II',
    clave: 'INGII',
    horas_semana: 8,
    semestre: 'Segundo',
  },
  {
    id: 14,
    nombre: 'Probabilidad y Estadística',
    clave: 'PRYES',
    horas_semana: 5,
    semestre: 'Sexto',
  },
  {
    id: 15,
    nombre: 'Matemáticas Aplicadas',
    clave: 'MTAPL',
    horas_semana: 4,
    semestre: 'Sexto',
  },
  {
    id: 16,
    nombre: 'Ciencias Sociales I',
    clave: 'CNSCI',
    horas_semana: 4,
    semestre: 'Segundo',
  },
]

export const materiasEmptyMock = [] // Para casos de prueba
