export const horarioDocente1 = [
  {
    grupo: '201A',
    semestre: 'Segundo',
    turno: 'Matutino',
    docente: 'Torres Quiñones Norma Elena',
    bloques: [
      {
        bloque: 1,
        hora: '7:00 a 7:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '406F',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MARTES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '406F',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '406F',
            semestre: 'Semestre IV',
          },
          {
            dia: 'JUEVES',
            clave: 'CNSEI',
            materia: 'Conservación de la Energía y sus Interacciones',
            grupo: '206F',
            semestre: 'Semestre II',
          },
          {
            dia: 'VIERNES',
            clave: 'CNSEI',
            materia: 'Conservación de la Energía y sus Interacciones',
            grupo: '206F',
            semestre: 'Semestre II',
          },
        ],
      },
      {
        bloque: 2,
        hora: '7:50 a 8:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'CNSEI',
            materia: 'Conservación de la Energía y sus Interacciones',
            grupo: '206F',
            semestre: 'Semestre II',
          },
          {
            dia: 'MARTES',
            clave: 'CNSEI',
            materia: 'Conservación de la Energía y sus Interacciones',
            grupo: '206F',
            semestre: 'Semestre II',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MULTD',
            materia: 'Multidisciplinarias',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
          {
            dia: 'VIERNES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
        ],
      },
      {
        hora: '8:40 a 9:10',
        receso: true,
      },
      {
        bloque: 3,
        hora: '9:10 a 10:00',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MARTES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 4,
        hora: '8:40 a 9:30',
        clases: [
          {
            dia: 'LUNES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MARTES',
            clave: 'TUTIN',
            materia: 'Tutorías Individuales',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MULTD',
            materia: 'Multidisciplinarias',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: 'OREDU',
            materia: 'Orientación Educativa',
            grupo: '608H',
            semestre: 'Semestre IV',
          },
          {
            dia: 'VIERNES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
        ],
      },
      {
        hora: '9:30 a 10:00',
        receso: true,
      },
      {
        bloque: 5,
        hora: '10:00 a 10:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'TUTOS',
            materia: 'Tutorías',
            grupo: '608H',
            semestre: 'Semestre VI',
          },
          {
            dia: 'MARTES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '205E',
            semestre: 'Semestre II',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
          {
            dia: 'JUEVES',
            clave: 'CMCOA',
            materia: 'Comisión Cordinación Asesorías',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: 'OREDU',
            materia: 'Orientación Educativa',
            grupo: '608H',
            semestre: 'Semestre VI',
          },
        ],
      },
      {
        bloque: 6,
        hora: '10:50 a 11:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '204D',
            semestre: 'Semestre II',
          },
          {
            dia: 'MARTES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '401A',
            semestre: 'Semestre IV',
          },
          {
            dia: 'JUEVES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '205E',
            semestre: 'Semestre II',
          },
          {
            dia: 'VIERNES',
            clave: 'CONCR',
            materia: 'Concurso',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 7,
        hora: '11:40 a 12:30',
        clases: [
          {
            dia: 'LUNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '205E',
            semestre: 'Semestre II',
          },
          {
            dia: 'MARTES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '204D',
            semestre: 'Semestre II',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '408H',
            semestre: 'Semestre IV',
          },
          {
            dia: 'JUEVES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '204D',
            semestre: 'Semestre II',
          },
          {
            dia: 'VIERNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '205E',
            semestre: 'Semestre II',
          },
        ],
      },
      {
        bloque: 8,
        hora: '12:30 a 13:20',
        clases: [
          {
            dia: 'LUNES',
            clave: 'RCQMC',
            materia: 'Reacciones Químicas',
            grupo: '408H',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MARTES',
            clave: 'CMCOA',
            materia: 'Comisión Cordinación Asesorías',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'ASACM',
            materia: 'Asesorías Académicas',
            grupo: '',
            semestre: 'Semestre II',
          },
          {
            dia: 'JUEVES',
            clave: 'TUTOS',
            materia: 'Tutorías',
            grupo: '608H',
            semestre: 'Semestre VI',
          },
          {
            dia: 'VIERNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '204D',
            semestre: 'Semestre II',
          },
        ],
      },
      {
        bloque: 9,
        hora: '13:20 a 14:10',
        clases: [
          {
            dia: 'LUNES',
            clave: 'ASACM',
            materia: 'Asesorías Académicas',
            grupo: '',
            semestre: 'Semestre IV',
          },
          {
            dia: 'MARTES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '203C',
            semestre: 'Semestre II',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '203C',
            semestre: 'Semestre II',
          },
          {
            dia: 'JUEVES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '203C',
            semestre: 'Semestre II',
          },
          {
            dia: 'VIERNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            grupo: '203C',
            semestre: 'Semestre II',
          },
        ],
      },
      {
        bloque: 10,
        hora: '14:10 a 15:00',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 11,
        hora: '15:00 a 15:50',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        hora: '15:50 a 16:20',
        receso: true,
      },
      {
        bloque: 12,
        hora: '16:20 a 17:10',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 13,
        hora: '17:10 a 18:00',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 14,
        hora: '18:00 a 18:50',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
      {
        bloque: 15,
        hora: '18:50 a 19:40',
        clases: [
          {
            dia: 'LUNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'Martes',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'MIÉRCOLES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'JUEVES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
          {
            dia: 'VIERNES',
            clave: '',
            materia: '',
            grupo: '',
            semestre: '',
          },
        ],
      },
    ],
  },
]
