// TODO: Generar nueva estructura sin recesos ni hora o con variable de hora.
export const horariosSemestre2 = [
  {
    grupo: '201A',
    semestre: 'Segundo',
    turno: 'Matutino',
    bloques: [
      {
        bloque: 1,
        hora: '7:00 a 7:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 2,
        hora: '7:50 a 8:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 3,
        hora: '9:10 a 10:00',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 4,
        hora: '10:00 a 10:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'JUEVES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 5,
        hora: '10:50 a 11:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A5',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'MARTES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'JUEVES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'VIERNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
        ],
      },
      {
        bloque: 6,
        hora: '11:40 a 12:30',
        clases: [
          {
            dia: 'LUNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'MARTES',
            clave: 'CDGII',
            materia: 'Cultura Digital II',
            aula: 'L2',
            docente: 'L. Jasso',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'CNSCL',
            materia: 'Ciencias Sociales',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'JUEVES',
            clave: 'CDGII',
            materia: 'Cultura Digital II',
            aula: 'L2',
            docente: 'L. Jasso',
          },
          {
            dia: 'VIERNES',
            clave: 'CNSCL',
            materia: 'Ciencias Sociales',
            aula: 'A6',
            docente: 'K. Moran',
          },
        ],
      },
      {
        bloque: 7,
        hora: '12:30 a 13:20',
        clases: [
          {
            dia: 'LUNES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
          { dia: 'MARTES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          { dia: 'MIÉRCOLES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          { dia: 'JUEVES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          {
            dia: 'VIERNES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
        ],
      },
      {
        bloque: 8,
        hora: '13:20 a 14:10',
        clases: [
          { dia: 'LUNES', clave: '', materia: '', aula: '', docente: '' },
          { dia: 'MARTES', clave: 'TUTOR', materia: 'Tutorías', aula: '', docente: 'R. Guadalupe' },
          {
            dia: 'MIÉRCOLES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'JUEVES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
          {
            dia: 'VIERNES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
        ],
      },
    ],
  },
  {
    grupo: '201A',
    semestre: 'Segundo',
    turno: 'Vespertino',
    bloques: [
      {
        bloque: 1,
        hora: '7:00 a 7:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 2,
        hora: '7:50 a 8:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 3,
        hora: '9:10 a 10:00',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'C5',
            docente: 'A. Díaz',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'JUEVES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 4,
        hora: '10:00 a 10:50',
        clases: [
          {
            dia: 'LUNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
          {
            dia: 'MARTES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'JUEVES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A6',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'VIERNES',
            clave: 'MODPR',
            materia: 'Módulo Profesional',
            aula: 'TMCI',
            docente: 'A. Díaz',
          },
        ],
      },
      {
        bloque: 5,
        hora: '10:50 a 11:40',
        clases: [
          {
            dia: 'LUNES',
            clave: 'PSMAT',
            materia: 'Pensamiento Matemático II',
            aula: 'A5',
            docente: 'Y. Cepeda',
          },
          {
            dia: 'MARTES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'JUEVES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'VIERNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
        ],
      },
      {
        bloque: 6,
        hora: '11:40 a 12:30',
        clases: [
          {
            dia: 'LUNES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'MARTES',
            clave: 'CDGII',
            materia: 'Cultura Digital II',
            aula: 'L2',
            docente: 'L. Jasso',
          },
          {
            dia: 'MIÉRCOLES',
            clave: 'CNSCL',
            materia: 'Ciencias Sociales',
            aula: 'A6',
            docente: 'K. Moran',
          },
          {
            dia: 'JUEVES',
            clave: 'CDGII',
            materia: 'Cultura Digital II',
            aula: 'L2',
            docente: 'L. Jasso',
          },
          {
            dia: 'VIERNES',
            clave: 'CNSCL',
            materia: 'Ciencias Sociales',
            aula: 'A6',
            docente: 'K. Moran',
          },
        ],
      },
      {
        bloque: 7,
        hora: '12:30 a 13:20',
        clases: [
          {
            dia: 'LUNES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
          { dia: 'MARTES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          { dia: 'MIÉRCOLES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          { dia: 'JUEVES', clave: 'EXTRC', materia: 'Extracurricular', aula: '', docente: '' },
          {
            dia: 'VIERNES',
            clave: 'LNYCM',
            materia: 'Lengua y Comunicación II',
            aula: 'A6',
            docente: 'K. Moran',
          },
        ],
      },
      {
        bloque: 8,
        hora: '13:20 a 14:10',
        clases: [
          { dia: 'LUNES', clave: '', materia: '', aula: '', docente: '' },
          { dia: 'MARTES', clave: 'TUTOR', materia: 'Tutorías', aula: '', docente: 'R. Guadalupe' },
          {
            dia: 'MIÉRCOLES',
            clave: 'CNENI',
            materia: 'Conservación de la Energía y sus interacciones',
            aula: 'A7',
            docente: 'L. Heredia',
          },
          {
            dia: 'JUEVES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
          {
            dia: 'VIERNES',
            clave: 'INGII',
            materia: 'Inglés II',
            aula: 'B3',
            docente: 'C. Rodríguez',
          },
        ],
      },
    ],
  },
]
